set PROJECT_HOME=%CD%
set ANT_HOME=%PROJECT_HOME%\PROJECTS-BASE\apache-ant-1.8.2
set JAVA_HOME=%PROJECT_HOME%\PROJECTS-BASE\jdk1.7.0_01
set HSQL_HOME=%PROJECT_HOME%\PROJECTS-EXT-LIB\hsqldb_1_8_0_10\hsqldb\lib
set PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin;%PATH%;